# Generated by Django 4.1.3 on 2023-01-22 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('envia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envia', to=settings.AUTH_USER_MODEL)),
                ('recibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
