# Generated by Django 4.1.3 on 2023-01-21 12:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_avatar_delete_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='cuerpo',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
