# Generated by Django 4.1.3 on 2023-01-21 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_alter_posteo_cuerpo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
