# Generated by Django 4.1.3 on 2023-01-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_remove_posteo_categoria_delete_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='cuerpo',
            field=models.TextField(),
        ),
    ]
