# Generated by Django 4.1.3 on 2023-01-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0005_alter_posteo_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='cuerpo',
            field=models.CharField(max_length=50),
        ),
    ]
