# Generated by Django 4.1.3 on 2023-01-21 13:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0007_rename_cuerpo_posteo_cuerpo2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='cuerpo2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
