# Generated by Django 4.1.3 on 2023-01-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0008_alter_posteo_cuerpo2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='imagen',
        ),
    ]
