# Generated by Django 4.1.3 on 2023-01-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0009_remove_posteo_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posteo',
            old_name='cuerpo2',
            new_name='cuerpo',
        ),
        migrations.AddField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='imagenes'),
        ),
    ]
