# Generated by Django 4.1.3 on 2023-01-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0010_rename_cuerpo2_posteo_cuerpo_posteo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='imagen',
        ),
    ]
