# Generated by Django 4.1.3 on 2023-01-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0011_remove_posteo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='imagenes'),
        ),
    ]
